### ISSUE TITLE
GitHub Actions observability?

### ISSUE THREAD

**Issue by petemounce** [promhippie/github_exporter#123] opened 2022-09-23 09:11 UTC
Do you have any plans to support exporting metrics around github actions?

I would find the following extremely useful to observe what I need to about github actions based workflows:

```txt
# counter
github_actions_workflow_count{event,org,repo,workflow_name,job_name,status,head_branch,runner_node_arch, runner_node_os, runner_node_type,retry_number}
# counter
github_actions_workflow_duration_ms{event,org,repo,workflow_name,job_name,status,head_branch,runner_node_arch, runner_node_os, runner_node_type,retry_number}

# event - the workflow-trigger event-name
# org, repo - the organisation and repository
# workflow_name - the name of the workflow
# job_name - the name of the job
# status - the workflow status - queued, in_progress, completed, etc
# head_branch - the name of the branch
# runner_node_* - details about the runner node
# retry_number - the retry count for the job
```

**Comment by tboerger** [comment] 2022-09-23 10:38
The cardinality of the labels is getting pretty high with that. Maybe this could be disabled by default and the collector can optionally get enabled for that.

**Comment by petemounce** [comment] 2022-09-23 13:22
I'd be totally fine with that. A flag like `[]string github_actions_labels` to take a validated whitelist sort of thing?

**Comment by norman-zon** [comment] 2023-03-07 08:48
Is this a feature you are planning to add to the project? I too would find it very useful!

**Comment by tboerger** [comment] 2023-03-08 16:09
So far I haven't done anything related to that. But I'm not entirely against it if it is disabled by default.

**Comment by tboerger** [comment] 2023-03-09 09:40
I will give it a try to get it implemented.

**Comment by tboerger** [comment] 2023-03-09 13:42
I have started to implement it at https://github.com/promhippie/github_exporter/pull/174 but I'm afraid that we will hit massively the rate limits of GitHub. Maybe somebody got an idea for a proper GraphQL query to fetch alle required information with lesser requests? I think the right REST API endpoint should be https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-required-workflow

**Comment by norman-zon** [comment] 2023-03-09 13:47
There is the (now abandoned) [github-actions-exporter](https://github.com/Spendesk/github-actions-exporter). Maybe this can give you some hints about the API usage.

**Comment by bradmccoydev** [comment] 2023-03-17 05:32
I am also very interested in this!!

**Comment by tboerger** [comment] 2023-03-17 07:45
I will continue on that, but currently I'm switching all my docker images to be pushed to quay and ghcr since docker announced I have to pay a lot of money to stay on dockerhub.

**Comment by tboerger** [comment] 2023-03-22 17:16
I have just merged my PR, please give the `latest` Docker image tag a try if thsi is really what you would expect. You are also welcome to take a look that the linked PR to get a better feeling about it. I would highly welcome some feedback as I personally have no need for these metrics.

**Comment by tboerger** [comment] 2023-03-22 17:16
If you need pre-compiled binaries I could tag some alpha or beta tag which would be uploaded to GitHub releases.

**Comment by tboerger** [comment] 2023-03-22 20:48
One tester already confirmed that it's working pretty nice. I have also updated the helm chart to support github app instead of token auth.

**Comment by tboerger** [comment] 2023-03-22 22:19
I'm closing this issue for now, but feel free to comment your findings or ideas how to improve this functionality.

**Closed by tboerger** 2023-03-22 22:19 UTC
Labels: enhancement

**Comment by bradmccoydev** [comment] 2023-03-22 23:56
What is the significance of the InstallationId in the helm chart in relation to the github app. Does it need the Client secret of the app? I cant see it in https://github.com/promhippie/github_exporter/blob/master/pkg/config/config.go

`# -- App ID used for GitHub app
  appId: ""

  # -- Key used within secret for appId
  appIdKey: appId

  # -- Installation ID used for GitHub app
  installationId: ""

  # -- Key used within secret for installationId
  installationIdKey: installationId`

**Comment by tboerger** [comment] 2023-03-23 06:16
When you are registering an application on GitHub you will receive an application ID, an installation ID and a private key. You got to provide all three of them to this exporter.

**Comment by rvoitenko** [comment] 2023-03-30 13:41
@tboerger thank you for the workflows metrics.
However, when I set `GITHUB_EXPORTER_COLLECTOR_WORKFLOWS=true` I still can't see any workflows metrics.
The token scope I'm using includes `workflow`. version 2.0.1
What I'm doing wrong?

**Comment by rvoitenko** [comment] 2023-03-30 14:31
> The collector gathers the workflows from enabled repos for the last 12 hours.

But I have many repos enabled in my organization with many workflows. Workflow runs happened many times during the last 12 hours.

**Comment by rvoitenko** [comment] 2023-03-31 06:17
> Have you looked into the logs of the exporter?

yes, I tried to run it with debug and error log level, no issues in the log. Only "Workflow collector registered" at startup.

**Comment by tboerger** [comment] 2023-03-31 06:28
Do you enable any public repository that I can use for debugging?

**Comment by tboerger** [comment] 2023-04-03 09:34
I can't reproduce your issue, but at least you will get a new version soon which includes more logs on debug loglevel, something similar to this:

```
level=debug ts=2023-04-03T09:32:27.406205167Z collector=workflow msg="Fetched workflows" count=108 duration=15.283556528s
level=debug ts=2023-04-03T09:32:27.406289803Z collector=workflow msg="Collecting workflow" owner=dockhippie/minecraft-forge name=lock
level=debug ts=2023-04-03T09:32:27.406340127Z collector=workflow msg="Collecting workflow" owner=dockhippie/minecraft-forge name=react
level=debug ts=2023-04-03T09:32:27.406366068Z collector=workflow msg="Collecting workflow" owner=dockhippie/mariadb name=latest
level=debug ts=2023-04-03T09:32:27.406391401Z collector=workflow msg="Collecting workflow" owner=dockhippie/mariadb name=react
level=debug ts=2023-04-03T09:32:27.406417658Z collector=workflow msg="Collecting workflow" owner=dockhippie/mariadb name=lock
```

**Comment by tboerger** [comment] 2023-04-03 10:59
I have merged a change that includes more log output if you set the loglevel to debug. For now it's only on `latest` available until I release v2.1.1.

**Comment by rvoitenko** [comment] 2023-04-05 19:36
Thank you.
I did one test with my private account, where I do not have many repos.
And I was able to see workflow metrics only when I defined variable `GITHUB_EXPORTER_REPO=MY_USERNAME/*`. But if I don't define this variable - no metrics are displayed, and there are no errors.

Another test I did with ORG, where there 100+ repos.
I've set `GITHUB_EXPORTER_ORG` and `GITHUB_EXPORTER_REPO=ORG_NAME/*` and got the following error:
`{"collector":"workflow","err":"context deadline exceeded","level":"error","msg":"Failed to fetch repo workflows"`

When I've changed `GITHUB_EXPORTER_REPO=ORG_NAME/*` to `GITHUB_EXPORTER_REPO=ORG_NAME/REPO_1`, where REPO_1 has 10-15 workflows run in the last 24 hours, I started to see workflow metrics, but only for this repo.
When I pointed this variable to `ORG_NAME/REPO_2` with 100+ workflows runs per 24h, or maybe even more, I got `context deadline exceeded` error again.

So it seems like the problem occurs when there are too many workflow runs. Also, I wonder if it's mandatory to define `GITHUB_EXPORTER_REPO/GITHUB_EXPORTER_REPOS` to make it work?

**Comment by petemounce** [comment] 2023-04-05 20:34
Re; `GITHUB_EXPORTER_REPO=ORG_NAME/*` - are you quoting there? I'm wondering if perhaps the * is being interpreted as a shell glob before being passed onward to the binary.

**Comment by tboerger** [comment] 2023-04-06 06:45
That sounds like the requests are running into a timeout, there is a flag and env variable to define a higher timeout value, please give that a try. You define the org variable for the orgs to gather metrics for, for gathering repo metrics you got to define the repo variable which supports globbing.

**Comment by tboerger** [comment] 2023-04-06 06:51
Oh and you should also increase the page size with the available variable if you got so many workflows and repos.

**Comment by rvoitenko** [comment] 2023-04-06 07:23
Yes, I've tried to increase the page size to 1000 and timeout to 300s, but it still can't handle many repos in ORG, only works for a single repo with not too many runs.

**Comment by apoorva-marisomaradhya** [comment] 2023-09-11 19:35
Hi @rvoitenko Were you able to get workflow related metrics? I am in a similar situation, where metrics related to workflows are missing.
Below is the logs from the exporter
`level=debug ts=2023-09-11T19:31:53.394863766Z collector=workflow msg="Fetched repos for workflows" count=0
level=debug ts=2023-09-11T19:31:53.394904406Z collector=workflow msg="Fetched workflows" count=0 duration=245.375386ms
level=debug ts=2023-09-11T19:31:53.590867875Z collector=runner msg="Fetched org runners" count=2 duration=223.888519ms`

I have also set `GITHUB_EXPORTER_COLLECTOR_WORKFLOWS` to true in the exporter configuration, any help would be highly appreciated.

**Comment by rvoitenko** [comment] 2023-09-11 21:30
> Hi @rvoitenko Were you able to get workflow related metrics? I am in a similar situation, where metrics related to workflows are missing. Below is the logs from the exporter `level=debug ts=2023-09-11T19:31:53.394863766Z collector=workflow msg="Fetched repos for workflows" count=0 level=debug ts=2023-09-11T19:31:53.394904406Z collector=workflow msg="Fetched workflows" count=0 duration=245.375386ms level=debug ts=2023-09-11T19:31:53.590867875Z collector=runner msg="Fetched org runners" count=2 duration=223.888519ms`
> 
> I have also set `GITHUB_EXPORTER_COLLECTOR_WORKFLOWS` to true in the exporter configuration, any help would be highly appreciated.

No, the bug still persists if you have a lot of repos/workflows. But it works if you limit the scope by pointing to a specific repo with `GITHUB_EXPORTER_REPO=ORG_NAME/REPO_1`

**Comment by apoorva-marisomaradhya** [comment] 2023-09-11 21:45
I have tried limiting the repo by setting `GITHUB_EXPORTER_REPO=ORG_NAME/REPO_1`, but still no metrics related `github_workflow_*` shows up.

**Comment by orensbruli** [comment] 2023-10-22 10:28
Same problem here :/
I have checked if it could be related to public/private repos but it does not. It fails for both.

**Comment by tboerger** [comment] 2023-10-22 11:39
The new webhooks are not finally released yet, but you can already try it with the latest image tag.

**Comment by orensbruli** [comment] 2023-10-22 12:11
Thank you so much. Unfortunately it's not a valid solution for us as we can't expose the machine to internet 😕 I have not found any other exporter that can get workflows information. Would it be possible to  get this behavior back?

**Comment by tboerger** [comment] 2023-10-23 05:15
Sadly I'm not really up for that anymore, most if not all reported issues of the past months have been related to the workflow exporter. 

The webhook implementation looks like the only reliable solution so far because of rate limits and the massive amount of repos the people got.

**Comment by orensbruli** [comment] 2023-10-23 05:40
No problem at all @tboerger Thank you for all your work on this!
Best.

**Comment by awalvie** [comment] 2023-11-28 13:12
> Sadly I'm not really up for that anymore, most if not all reported issues of the past months have been related to the workflow exporter.
> 
> The webhook implementation looks like the only reliable solution so far because of rate limits and the massive amount of repos the people got.

Hey! Brilliant project this. We're trying to use this exporter and running into the same issue where we cannot expose the machine to the public internet and can't get workflow information about metrics without webhooks.

If you're alright with it do you think I could add support for it? An optional to either use the webhooks or support polling the github api even if there are rate limiting issues?

**Comment by tboerger** [comment] 2023-11-29 08:32
Sorry but currently I'm not planning to add an alternative as this had been really a pain to support. You can easily set this runner up pretty secure, it offers multiple options for authenticated access so that it could be easily available from the internet, or you could just forward the GitHub webhook endpoint which requires an authentication token by default anyway.
